In [1]:
import pandas as pd
import numpy as np

In [2]:
car = pd.read_csv('quicker_car.csv')

In [3]:
car.head(25)

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
5,5,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel
6,6,Ford Figo,Ford,2012,"1,75,000","41,000 kms",Diesel
7,7,Hyundai Eon,Hyundai,2013,"1,90,000","25,000 kms",Petrol
8,8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,"8,30,000","24,530 kms",Diesel
9,9,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,"2,50,000","60,000 kms",Petrol
10,10,Skoda Fabia Classic 1.2 MPI,Skoda,2010,"1,82,000","60,000 kms",Petrol
11,11,Maruti Suzuki Stingray VXi,Maruti,2015,"3,15,000","30,000 kms",Petrol
12,12,Hyundai Elite i20 Magna 1.2,Hyundai,2014,"4,15,000","32,000 kms",Petrol
13,13,Mahindra Scorpio SLE BS IV,Mahindra,2015,"3,20,000","48,660 kms",Diesel
14,14,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
15,15,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
16,16,Audi A8,Audi,2017,"10,00,000","4,000 kms",Petrol
17,17,Audi Q7,Audi,2014,"5,00,000","16,934 kms",Diesel
18,18,Mahindra Scorpio S10,Mahindra,2016,"3,50,000","43,000 kms",Diesel
19,19,Maruti Suzuki Alto 800,Maruti,2014,"1,60,000","35,550 kms",Petrol
20,20,Mahindra Scorpio S10,Mahindra,2016,"3,50,000","43,000 kms",Diesel
21,21,Mahindra Scorpio S10,Mahindra,2016,"3,10,000","39,522 kms",Diesel
22,22,Maruti Suzuki Alto 800 Vxi,Maruti,2015,"75,000","39,000 kms",Petrol
23,23,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol
24,24,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol

In [4]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  892 non-null    int64
 1   name        892 non-null    object
 2   company     892 non-null    object
 3   year        892 non-null    object
 4   Price       892 non-null    object
 5   kms_driven  840 non-null    object
 6   fuel_type   837 non-null    object
dtypes: int64(1), object(6)
memory usage: 48.9+ KB

In [5]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

## quality
-year hass many non year values
-year object to int
-price has ask for price
- price object to int kms_driven has kms with integer
- kms driven object to int kms_driven has nan values
- keep first 3 words of name
-

# Cleaning

In [6]:
backup = car.copy()

In [7]:
car =car[car['year'].str.isnumeric()]

In [8]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...,...
886,886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [9]:
car['year'] = car['year'].astype(int)

In [10]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...,...
886,886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [11]:
car = car[car['Price']!="Ask For Price"]

In [12]:
car['Price'] = car['Price'].str.replace(',','').astype(int)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_18968\2973828468.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['Price'] = car['Price'].str.replace(',','').astype(int)

In [13]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,"45,000 kms",Petrol
1,1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40 kms,Diesel
3,3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,"28,000 kms",Petrol
4,4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,"36,000 kms",Diesel
6,6,Ford Figo,Ford,2012,175000,"41,000 kms",Diesel
...,...,...,...,...,...,...,...
886,886,Toyota Corolla Altis,Toyota,2009,300000,"1,32,000 kms",Petrol
888,888,Tata Zest XM Diesel,Tata,2018,260000,"27,000 kms",Diesel
889,889,Mahindra Quanto C8,Mahindra,2013,390000,"40,000 kms",Diesel
890,890,Honda Amaze 1.2 E i VTEC,Honda,2014,180000,Petrol,NaN
891,891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,160000,Petrol,NaN

In [14]:
car['kms_driven'] = car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

C:\Users\lenovo\AppData\Local\Temp\ipykernel_18968\560589238.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['kms_driven'] = car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [15]:
car = car[car['kms_driven'].str.isnumeric()]

In [16]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
883,883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [17]:
 car['kms_driven'] = car['kms_driven'].astype(int)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_18968\3578356754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['kms_driven'] = car['kms_driven'].astype(int)

In [18]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
883,883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [19]:
car = car[~car['fuel_type'].isna()]

In [20]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
883,883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [21]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')

C:\Users\lenovo\AppData\Local\Temp\ipykernel_18968\3677590539.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [22]:
car = car.reset_index(drop=True)

In [23]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,3,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,4,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
811,883,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
812,885,Tata Indica V2,Tata,2009,110000,30000,Diesel
813,886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
814,888,Tata Zest XM,Tata,2018,260000,27000,Diesel
815,889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [24]:
car = car.drop('Unnamed: 0',axis = 1)

In [25]:
car = car[car['Price']<6e6].reset_index(drop = True)

In [26]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [27]:
car.to_csv('clean_car.csv')

# Model

In [28]:
x = car.drop(columns = 'Price')
y = car['Price']

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2)

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [31]:
one =  OneHotEncoder()
one.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [32]:
colum_Trans = make_column_transformer((OneHotEncoder(categories  = one.categories_),['name','company','fuel_type']),remainder = 'passthrough')

In [33]:
lr = LinearRegression()

In [34]:
pipe = make_pipeline(colum_Trans,lr)

In [35]:
pipe.fit(X_train,Y_train)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [36]:
Y_pred = pipe.predict(X_test)

In [37]:
r2_score(Y_test,Y_pred)

0.673084284955042

In [38]:
scores = []
for i in range(1000):
    X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2,random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(colum_Trans,lr)
    pipe.fit(X_train,Y_train)
    Y_pred = pipe.predict(X_test)
    scores.append(r2_score(Y_test,Y_pred))

In [39]:
np.argmax(scores)

np.int64(433)

In [40]:
scores[np.argmax(scores)]

0.8456957793726847

In [41]:
for i in range(10):
     X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2,random_state = np.argmax(scores))
     lr = LinearRegression()
     pipe = make_pipeline(colum_Trans,lr)
     pipe.fit(X_train,Y_train)
     Y_pred = pipe.predict(X_test)
     print(r2_score(Y_test,Y_pred),i)

0.8456957793726847 0
0.8456957793726847 1
0.8456957793726847 2
0.8456957793726847 3
0.8456957793726847 4
0.8456957793726847 5
0.8456957793726847 6
0.8456957793726847 7
0.8456957793726847 8
0.8456957793726847 9

In [42]:
import pickle

In [43]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [44]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],columns =['name','company','year','kms_driven','fuel_type']))

array([458934.66740154])